# Generated by Django 3.0.6 on 2020-06-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='article_title',
        ),
    ]
