# Generated by Django 2.2.6 on 2019-10-27 18:58

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='article_subtitle',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='article_title',
            field=models.CharField(default='Awesome Title', max_length=255),
            preserve_default=False,
        ),
    ]
