# Generated by Django 2.2.6 on 2019-12-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191027_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='article_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
    ]
