# Generated by Django 2.2.9 on 2019-12-21 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191203_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
