# Generated by Django 2.2.9 on 2019-12-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_articlepage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
