# Generated by Django 2.2.9 on 2020-02-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_articlepage_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
    ]
