# Generated by Django 3.0.3 on 2020-02-07 02:45

import core.blocks
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_articlepage_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='code',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='is_article',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext_editor', core.blocks.RichTextBlock()), ('code_block', wagtail.core.blocks.StreamBlock([('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))]))]))], blank=True, null=True),
        ),
    ]
