# Generated by Django 3.0.3 on 2020-03-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200217_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='cover_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
