# Generated by Django 3.0.4 on 2020-03-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_articlepage_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='headline',
            field=models.CharField(max_length=255),
        ),
    ]
