# Generated by Django 3.0.4 on 2020-03-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200308_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='twitter_link',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
